### ISSUE TITLE
Why use stream for warehouse#save()?

### ISSUE THREAD

**Issue by segayuu** [hexojs/warehouse#20]
The output by stream is obviously slower than `fs.writeFile()`.
Nevertheless, stream is powerful because memory control by `highWaterMark` can prevent memory from being consumed too much at once.
However, this can not be realized with just `Writable` alone (at least `Readable` or `Generator` is almost required), you can ignore it, but in that case no memory control will be done and the stream loses its maximum advantage.
Although it is possible to use `JSONStream.stringnify()`, it is said that an issue has been posted, ["It is 100 times slower than JSON.sringnify()"](https://github.com/dominictarr/JSONStream/issues/131).

**Comment by segayuu** [comment]
How stream performs memory management is described in this official document.
https://nodejs.org/en/docs/guides/backpressuring-in-streams/#how-does-backpressure-resolve-these-issues

**Comment by segayuu** [comment]
We improved this issue at #22.

**Comment by SukkaW** [comment]
Well, after #22, the speed of saving database seems to become 6x slower based on https://github.com/hexojs/hexo/issues/3758 . We should have a look at this.

**Comment by stevenjoezhang** [comment]
Fixed in https://github.com/hexojs/warehouse/pull/62
