### ISSUE TITLE
removeById works, but remove doesn't

### ISSUE THREAD

**Issue by FXNanN** [hexojs/warehouse#272]
### Check List

- [X] I have already read README.
- [X] I have already searched existing issues and they are not help to me.
- [X] I examined error or warning messages and it's difficult to solve.
- [X] I am using the latest version of this repository.
- [X] I am using the [latest](https://github.com/hexojs/hexo/releases) version of Hexo.
- [X] My Node.js is matched the required version.

### Describe the bug

warehouse@5.0.1

removeById works as expected, but remove doesn't. 

### Expected behavior

After each remove finished, the count() should reduce. 

### How to reproduce

```javascript
hexo.extend.filter.register("before_generate", function() {
    let posts_db_model = this.model("Post");

    posts_db_model.forEach((post) => {
        console.log(`remove: ${get_post_md_path(post)}`);
        posts_db_model.remove(post).then(() => {
            console.log(`after 1 remove: ${posts_db_model.count()}`);
        });
    }); // not working

    posts_db_model.forEach((post) => {
        console.log(`remove: ${get_post_md_path(post)}`);
        posts_db_model.removeById(post._id).then(() => {
            console.log(`after 1 remove: ${posts_db_model.count()}`);
        });
    }); // working

}, 11);
```

**Comment by yoshinorin** [comment]
@FXNanN 

Please try changing the code as follows.

```diff
hexo.extend.filter.register("before_generate", function() {
    let posts_db_model = this.model("Post");

    posts_db_model.forEach((post) => {
        console.log(`remove: ${get_post_md_path(post)}`);
-        posts_db_model.remove(post).then(() => {
+        post.remove().then(() => {
            console.log(`after 1 remove: ${posts_db_model.count()}`);
        });
    }); // not working

    posts_db_model.forEach((post) => {
        console.log(`remove: ${get_post_md_path(post)}`);
        posts_db_model.removeById(post._id).then(() => {
            console.log(`after 1 remove: ${posts_db_model.count()}`);
        });
    }); // working

}, 11);
```

I think the [test code of Hexo](https://github.com/hexojs/hexo/blob/07781d8d6c057229761675004b3ec22753df2a88/test/scripts/filters/render_post.ts#L31) will be helpful.

Thanks :)

**Comment by FXNanN** [comment]
@yoshinorin Thank you!
