### ISSUE TITLE
Release warehouse@4

### ISSUE THREAD

**Issue by SukkaW** [hexojs/warehouse#83]
We should release a newer version of warehouse in order to include #78, #79, #80, #81 

cc @segayuu @curbengh @YoshinoriN @hexojs/core

**Comment by segayuu** [comment]
#82 IMO it is preferable to include # 82 PR for this issue.

**Comment by SukkaW** [comment]
@segayuu As hexo@5 supposed to use Node.js 10.13.0 as minimum required Node.js version.

Unless a polyfill or a workaround is provided, otherwise #82 shouldn't be included.

**Comment by segayuu** [comment]
@SukkaW OK, I will follow your opinion.

**Comment by YoshinoriN** [comment]
@SukkaW @segayuu 
cc @hexojs/core 

I'm going to release `4.0.0` after merge #87

Thank you :)

**Comment by SukkaW** [comment]
@YoshinoriN Approved.

**Comment by YoshinoriN** [comment]
Done: https://www.npmjs.com/package/warehouse/v/4.0.0
I will write news after tomorrow :)
